global:
  scrape_interval:     60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
 
  - job_name: linux
    static_configs:
      - targets: ['192.168.203.135:9100']
        labels:
          instance: localhost
  - job_name: "prd_mysql"
    file_sd_configs:
      - files: ['/usr/local/prometheus/sd_config/prd_mysql.json']
        refresh_interval: 120s