networks:
  1panel-network:
    external: true
services:
  postgresql:
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      - POSTGRES_USER=${PANEL_DB_ROOT_USER}
      - POSTGRES_PASSWORD=${PANEL_DB_ROOT_PASSWORD}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD
        - pg_isready
        - -h
        - 127.0.0.1
        - -p
        - "5432"
        - -q
        - -U
        - ${PANEL_DB_ROOT_USER}
      timeout: 5s
    image: postgres:16.3-alpine
    labels:
      createdBy: Apps
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5432
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
