networks:
  1panel-network:
    external: true
services:
  nacos:
    container_name: ${CONTAINER_NAME}-standalone
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE:-FALSE}
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=${JVM_XMS}
      - JVM_XMX=${JVM_XMX}
      - JVM_XMN=${JVM_XMN}
      - JVM_MS=${JVM_MS}
      - JVM_MMS=${JVM_MMS}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_SERVER_IP=${NACOS_SERVER_IP}
    image: nacos/nacos-server:v2.3.2
    ports:
      - ${PANEL_APP_PORT_HTTP}:8848
      - ${PANEL_APP_PORT_COMMUNICATION}:9848
    restart: always
    volumes:
      - ./data/logs:/home/nacos/logs
      - ./data/data:/home/nacos/data
